name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Miki.UrbanDictionary.sln'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
        
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 6

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      env: 
        BUILD_ID: ${{ github.run_id }}

    - name: Run tests
      run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      run: dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate